services:
    app:
        image: fudaoyuanicu/015-app:latest
        container_name: 015-app
        volumes:
            - ./uploads:/uploads
            - ./config.yaml:/app/config.yaml
        ports:
            - '8080:80'
        depends_on:
            - redis

    worker:
        image: fudaoyuanicu/015-worker:latest
        container_name: worker
        volumes:
            - ./uploads:/uploads
            - ./config.yaml:/config.yaml
        depends_on:
            - app
            - redis
    redis:
        image: redis:7
        container_name: redis
